name: niamu_project
description: "Projekt za kolegij Napredna izrada aplikacija za mobilne uređaje"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.0
  cupertino_icons: ^1.0.6
  lottie: ^3.1.2
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.4.0
  flutter_hooks: ^0.20.5
  reactive_forms: ^17.0.1
  dio: ^5.7.0
  firebase_auth: ^5.3.1
  logger: ^2.4.0
  dartz: ^0.10.1
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  firebase_core: ^3.6.0
  control_style: ^0.1.0
  cached_network_image: ^3.4.1
  retrofit: ^4.4.0
  json_annotation: ^4.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.8.0
  retrofit_generator: '^8.2.1'
  hive_generator: ^2.0.1


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/animations/
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

